CREATE OR REPLACE FUNCTION FN_GET_USER_PASSWORD(
	I_USER_NUMBER IN VARCHAR
)RETURNS TABLE (
	USER_NUMBER VARCHAR,
	HASHED_PASSWORD VARCHAR,
	EMAIL VARCHAR
)
LANGUAGE PLPGSQL
AS $$
BEGIN
	RETURN QUERY
		SELECT 
			U.USER_NUMBER,
			U.HASHED_PASSWORD,
			U.EMAIL
		FROM
			USERS U
		WHERE
			U.USER_NUMBER = I_USER_NUMBER
	
	;
END;
$$;

CREATE OR REPLACE FUNCTION FN_UPDATE_USER_LOGIN_TIME(
	I_USER_NUMBER IN VARCHAR
)RETURNS INTEGER
LANGUAGE PLPGSQL
AS $$
DECLARE
	UPDATE_ROWS INTEGER;
BEGIN
	UPDATE
		USERS
	SET
		LAST_LOGIN_TIME = NOW()
	WHERE
		USER_NUMBER = I_USER_NUMBER
	;
	GET DIAGNOSTICS UPDATE_ROWS = ROW_COUNT;
	
	RETURN UPDATE_ROWS;
END;
$$;
	