CREATE OR REPLACE FUNCTION FN_GET_USER_PASSWORD(
	I_USER_NUMBER IN VARCHAR
)RETURNS TABLE (
	USER_NUMBER VARCHAR,
	HASHED_PASSWORD VARCHAR,
	EMAIL VARCHAR
)
LANGUAGE PLPGSQL
AS $$
BEGIN
	RETURN QUERY
		SELECT 
			U.USER_NUMBER,
			U.HASHED_PASSWORD,
			U.EMAIL
		FROM
			USERS U
		WHERE
			U.USER_NUMBER = I_USER_NUMBER
	
	;
END;
$$;