CREATE OR REPLACE PROCEDURE get_permission_by_user_id(
    I_USER_NUMBER IN VARCHAR,
    o_cursor_name INOUT REFCURSOR
)
LANGUAGE plpgsql
AS $$
BEGIN
  OPEN o_cursor_name FOR 
      SELECT
	      R.ID,
		  R.SYSTEM_ID,
		  R.RESOURCE_NAME,
		  R.RESOURCE_IDENTIFIER,
		  R.DESCRIPTION
      FROM
	      USERS U
		  INNER JOIN USER_GROUPS UG ON U.ID = UG.USER_ID
		  INNER JOIN GROUP_ROLES GR ON GR.GROUP_ID = UG.GROUP_ID
		  INNER JOIN PERMISSIONS P ON P.ROLE_ID = GR.ROLE_ID
		  INNER JOIN RESOURCES R ON R.ID = P.RESOURCE_ID
	  WHERE
	      U.USER_NUMBER = I_USER_NUMBER
  ;                             
END;
$$;